[package]
name = "keygen"
version = "1.9.29"
description = ""
authors = [""]
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""
edition = "2021"

[dependencies]
bs58 = "0.4.0"
clap = "2.33"
dirs-next = "2.0.0"
num_cpus = "1.13.1"
clap-utils = { path = "../clap-utils", version = "=1.9.29" }
cli-config = { path = "../cli-config", version = "=1.9.29" }
remote-wallet = { path = "../remote-wallet", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
version = { path = "../version", version = "=0.6.3" }
tiny-bip39 = "0.8.2"

[[bin]]
name = "sino-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
