[package]
name = "perf"
version = "1.9.29"
description = "Performance APIs"
authors = [""]
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""
edition = "2021"

[dependencies]
bincode = "1.3.3"
curve25519-dalek = { version = "3" }
ahash = "0.7.6"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
lazy_static = "1.4.0"
bv = { version = "0.11.1", features = ["serde"] }
fnv = "1.0.7"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
serde = "1.0.130"
bloom = { path = "../bloom", version = "=1.9.29" }
logger = { path = "../logger", version = "=1.9.29" }
metrics = { path = "../metrics", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
vote-program = { path = "../programs/vote", version = "=1.9.29" }
rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.29" }

[target."cfg(target_os = \"linux\")".dependencies]
caps = "0.5.3"
libc = "0.2.108"
nix = "0.23.0"

[lib]
name = "perf"

[dev-dependencies]
matches = "0.1.9"

[[bench]]
name = "sigverify"

[[bench]]
name = "discard"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
