[package]
name = "sdk-macro"
version = "1.9.29"
description = "SDK Macro"
authors = [""]
repository = ""
homepage = ""
documentation = "https://docs.rs/sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
