[package]
name = "metrics"
version = "1.9.29"
description = "Metrics"
authors = [""]
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""
edition = "2021"

[dependencies]
env_logger = "0.9.0"
gethostname = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
sdk = { path = "../sdk", version = "=1.9.29" }

[dev-dependencies]
rand = "0.7.0"
serial_test = "0.5.1"

[lib]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
